name = "Confluence"
author = "ShawnPad"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "119b9b3e15e2e3fcbb7d7ca87ff14f857caa53a67fe7a0752e6b217ee7d84f95"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
