name = "Confluence"
author = "ShawnPad"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb7a0dd2d64aefc3f5ecf65a6ab5d4a340a3708ae229c53f62ceeecc214470b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
