name = "Confluence"
author = "ShawnPad"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a521d7f61fc4eb441bdac691e7cc90300213f3996c2ec97fdf83a15f5fd9a15f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
