#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

packwiz modrinth install "mekanism" -y || echo "INSTALL FAILED: mekanism (modrinth)"
packwiz modrinth install "kubejs-mekanism" -y || echo "INSTALL FAILED: kubejs-mekanism (modrinth)"
packwiz modrinth install "mekanism-generators" -y || echo "INSTALL FAILED: mekanism-generators (modrinth)"
packwiz modrinth install "industrial-foregoing" -y || echo "INSTALL FAILED: industrial-foregoing (modrinth)"
packwiz modrinth install "powah" -y || echo "INSTALL FAILED: powah (modrinth)"
packwiz modrinth install "ars-nouveau" -y || echo "INSTALL FAILED: ars-nouveau (modrinth)"
packwiz modrinth install "ars-additions" -y || echo "INSTALL FAILED: ars-additions (modrinth)"
packwiz curseforge install "irons-spells-n-spellbooks" -y --category mc-mods || echo "INSTALL FAILED: irons-spells-n-spellbooks (curseforge)"
packwiz modrinth install "ad-astra" -y || echo "INSTALL FAILED: ad-astra (modrinth)"
packwiz modrinth install "ae2" -y || echo "INSTALL FAILED: ae2 (modrinth)"
packwiz modrinth install "toms-storage" -y || echo "INSTALL FAILED: toms-storage (modrinth)"
packwiz curseforge install "functional-storage" -y --category mc-mods || echo "INSTALL FAILED: functional-storage (curseforge)"
packwiz modrinth install "sophisticated-storage" -y || echo "INSTALL FAILED: sophisticated-storage (modrinth)"
packwiz modrinth install "sophisticated-backpacks" -y || echo "INSTALL FAILED: sophisticated-backpacks (modrinth)"
packwiz modrinth install "allthemodium" -y || echo "INSTALL FAILED: allthemodium (modrinth)"
packwiz curseforge install "the-twilight-forest" -y --category mc-mods || echo "INSTALL FAILED: the-twilight-forest (curseforge)"
packwiz modrinth install "the-undergarden" -y || echo "INSTALL FAILED: the-undergarden (modrinth)"
packwiz modrinth install "aether" -y || echo "INSTALL FAILED: aether (modrinth)"
packwiz modrinth install "deeperdarker" -y || echo "INSTALL FAILED: deeperdarker (modrinth)"
packwiz modrinth install "the-bumblezone" -y || echo "INSTALL FAILED: the-bumblezone (modrinth)"
packwiz modrinth install "l_enders-cataclysm" -y || echo "INSTALL FAILED: l_enders-cataclysm (modrinth)"
packwiz modrinth install "eternal-starlight" -y || echo "INSTALL FAILED: eternal-starlight (modrinth)"
packwiz modrinth install "mystical-agriculture" -y || echo "INSTALL FAILED: mystical-agriculture (modrinth)"
packwiz modrinth install "mystical-agradditions" -y || echo "INSTALL FAILED: mystical-agradditions (modrinth)"
packwiz curseforge install "productivebees" -y --category mc-mods || echo "INSTALL FAILED: productivebees (curseforge)"
packwiz modrinth install "almostunified" -y || echo "INSTALL FAILED: almostunified (modrinth)"
packwiz modrinth install "kubejs" -y || echo "INSTALL FAILED: kubejs (modrinth)"
packwiz modrinth install "lootjs" -y || echo "INSTALL FAILED: lootjs (modrinth)"
packwiz curseforge install "ftb-quests-forge" -y --category mc-mods || echo "INSTALL FAILED: ftb-quests-forge (curseforge)"
packwiz curseforge install "ftb-library-forge" -y --category mc-mods || echo "INSTALL FAILED: ftb-library-forge (curseforge)"
packwiz curseforge install "ftb-teams-forge" -y --category mc-mods || echo "INSTALL FAILED: ftb-teams-forge (curseforge)"
packwiz curseforge install "ftb-xmod-compat" -y --category mc-mods || echo "INSTALL FAILED: ftb-xmod-compat (curseforge)"
packwiz modrinth install "supplementaries" -y || echo "INSTALL FAILED: supplementaries (modrinth)"
packwiz modrinth install "amendments" -y || echo "INSTALL FAILED: amendments (modrinth)"
packwiz modrinth install "farmers-delight" -y || echo "INSTALL FAILED: farmers-delight (modrinth)"
packwiz modrinth install "cooking-for-blockheads" -y || echo "INSTALL FAILED: cooking-for-blockheads (modrinth)"
packwiz modrinth install "macaws-bridges" -y || echo "INSTALL FAILED: macaws-bridges (modrinth)"
packwiz modrinth install "macaws-doors" -y || echo "INSTALL FAILED: macaws-doors (modrinth)"
packwiz modrinth install "macaws-fences-and-walls" -y || echo "INSTALL FAILED: macaws-fences-and-walls (modrinth)"
packwiz modrinth install "macaws-furniture" -y || echo "INSTALL FAILED: macaws-furniture (modrinth)"
packwiz modrinth install "macaws-lights-and-lamps" -y || echo "INSTALL FAILED: macaws-lights-and-lamps (modrinth)"
packwiz modrinth install "macaws-paths-and-pavings" -y || echo "INSTALL FAILED: macaws-paths-and-pavings (modrinth)"
packwiz modrinth install "macaws-roofs" -y || echo "INSTALL FAILED: macaws-roofs (modrinth)"
packwiz modrinth install "macaws-stairs" -y || echo "INSTALL FAILED: macaws-stairs (modrinth)"
packwiz modrinth install "macaws-trapdoors" -y || echo "INSTALL FAILED: macaws-trapdoors (modrinth)"
packwiz modrinth install "macaws-windows" -y || echo "INSTALL FAILED: macaws-windows (modrinth)"
packwiz curseforge install "refurbished-furniture" -y --category mc-mods || echo "INSTALL FAILED: refurbished-furniture (curseforge)"
packwiz modrinth install "handcrafted" -y || echo "INSTALL FAILED: handcrafted (modrinth)"
packwiz modrinth install "chipped" -y || echo "INSTALL FAILED: chipped (modrinth)"
packwiz modrinth install "rechiseled" -y || echo "INSTALL FAILED: rechiseled (modrinth)"
packwiz modrinth install "framedblocks" -y || echo "INSTALL FAILED: framedblocks (modrinth)"
packwiz modrinth install "connected-glass" -y || echo "INSTALL FAILED: connected-glass (modrinth)"
packwiz modrinth install "oh-the-biomes-weve-gone" -y || echo "INSTALL FAILED: oh-the-biomes-weve-gone (modrinth)"
packwiz modrinth install "regions-unexplored" -y || echo "INSTALL FAILED: regions-unexplored (modrinth)"
packwiz modrinth install "yungs-api" -y || echo "INSTALL FAILED: yungs-api (modrinth)"
packwiz modrinth install "yungs-better-dungeons" -y || echo "INSTALL FAILED: yungs-better-dungeons (modrinth)"
packwiz modrinth install "yungs-better-strongholds" -y || echo "INSTALL FAILED: yungs-better-strongholds (modrinth)"
packwiz modrinth install "yungs-better-mineshafts" -y || echo "INSTALL FAILED: yungs-better-mineshafts (modrinth)"
packwiz modrinth install "yungs-better-nether-fortresses" -y || echo "INSTALL FAILED: yungs-better-nether-fortresses (modrinth)"
packwiz modrinth install "yungs-better-caves" -y || echo "INSTALL FAILED: yungs-better-caves (modrinth)"
packwiz modrinth install "formations" -y || echo "INSTALL FAILED: formations (modrinth)"
packwiz modrinth install "formations-overworld" -y || echo "INSTALL FAILED: formations-overworld (modrinth)"
packwiz modrinth install "formations-nether" -y || echo "INSTALL FAILED: formations-nether (modrinth)"
packwiz modrinth install "structory" -y || echo "INSTALL FAILED: structory (modrinth)"
packwiz modrinth install "towns-and-towers" -y || echo "INSTALL FAILED: towns-and-towers (modrinth)"
packwiz modrinth install "when-dungeons-arise" -y || echo "INSTALL FAILED: when-dungeons-arise (modrinth)"
packwiz modrinth install "lootr" -y || echo "INSTALL FAILED: lootr (modrinth)"
packwiz modrinth install "jei" -y || echo "INSTALL FAILED: jei (modrinth)"
packwiz modrinth install "jade" -y || echo "INSTALL FAILED: jade (modrinth)"
packwiz modrinth install "journeymap" -y || echo "INSTALL FAILED: journeymap (modrinth)"
packwiz modrinth install "appleskin" -y || echo "INSTALL FAILED: appleskin (modrinth)"
packwiz modrinth install "mouse-tweaks" -y || echo "INSTALL FAILED: mouse-tweaks (modrinth)"
packwiz modrinth install "controlling" -y || echo "INSTALL FAILED: controlling (modrinth)"
packwiz modrinth install "polymorph" -y || echo "INSTALL FAILED: polymorph (modrinth)"
packwiz modrinth install "explorers-compass" -y || echo "INSTALL FAILED: explorers-compass (modrinth)"
packwiz modrinth install "natures-compass" -y || echo "INSTALL FAILED: natures-compass (modrinth)"
packwiz modrinth install "waystones" -y || echo "INSTALL FAILED: waystones (modrinth)"
packwiz modrinth install "corail-tombstone" -y || echo "INSTALL FAILED: corail-tombstone (modrinth)"
packwiz curseforge install "ftb-chunks-forge" -y --category mc-mods || echo "INSTALL FAILED: ftb-chunks-forge (curseforge)"
packwiz curseforge install "ftb-ultimine-forge" -y --category mc-mods || echo "INSTALL FAILED: ftb-ultimine-forge (curseforge)"
packwiz curseforge install "ftb-essentials" -y --category mc-mods || echo "INSTALL FAILED: ftb-essentials (curseforge)"
packwiz modrinth install "clumps" -y || echo "INSTALL FAILED: clumps (modrinth)"
packwiz modrinth install "enchantment-descriptions" -y || echo "INSTALL FAILED: enchantment-descriptions (modrinth)"
packwiz modrinth install "sodium" -y || echo "INSTALL FAILED: sodium (modrinth)"
packwiz modrinth install "iris" -y || echo "INSTALL FAILED: iris (modrinth)"
packwiz modrinth install "lithium" -y || echo "INSTALL FAILED: lithium (modrinth)"
packwiz modrinth install "modernfix" -y || echo "INSTALL FAILED: modernfix (modrinth)"
packwiz modrinth install "ferrite-core" -y || echo "INSTALL FAILED: ferrite-core (modrinth)"
packwiz modrinth install "entityculling" -y || echo "INSTALL FAILED: entityculling (modrinth)"
packwiz modrinth install "immediatelyfast" -y || echo "INSTALL FAILED: immediatelyfast (modrinth)"
packwiz modrinth install "packet-fixer" -y || echo "INSTALL FAILED: packet-fixer (modrinth)"
packwiz modrinth install "alternate-current" -y || echo "INSTALL FAILED: alternate-current (modrinth)"
packwiz modrinth install "badoptimizations" -y || echo "INSTALL FAILED: badoptimizations (modrinth)"
packwiz modrinth install "dynamic-fps" -y || echo "INSTALL FAILED: dynamic-fps (modrinth)"
packwiz modrinth install "spark" -y || echo "INSTALL FAILED: spark (modrinth)"
packwiz modrinth install "chunky" -y || echo "INSTALL FAILED: chunky (modrinth)"
packwiz modrinth install "architectury-api" -y || echo "INSTALL FAILED: architectury-api (modrinth)"
packwiz modrinth install "rhino" -y || echo "INSTALL FAILED: rhino (modrinth)"
packwiz modrinth install "better-advanced-tooltips" -y || echo "INSTALL FAILED: better-advanced-tooltips (modrinth)"
packwiz modrinth install "geckolib" -y || echo "INSTALL FAILED: geckolib (modrinth)"
packwiz modrinth install "curios" -y || echo "INSTALL FAILED: curios (modrinth)"
packwiz modrinth install "irons-lib" -y || echo "INSTALL FAILED: irons-lib (modrinth)"
packwiz modrinth install "playeranimator" -y || echo "INSTALL FAILED: playeranimator (modrinth)"
packwiz modrinth install "titanium" -y || echo "INSTALL FAILED: titanium (modrinth)"
packwiz modrinth install "cucumber" -y || echo "INSTALL FAILED: cucumber (modrinth)"
packwiz modrinth install "resourceful-lib" -y || echo "INSTALL FAILED: resourceful-lib (modrinth)"
packwiz modrinth install "resourceful-config" -y || echo "INSTALL FAILED: resourceful-config (modrinth)"
packwiz modrinth install "common-storage-lib" -y || echo "INSTALL FAILED: common-storage-lib (modrinth)"
packwiz modrinth install "balm" -y || echo "INSTALL FAILED: balm (modrinth)"
packwiz modrinth install "moonlight" -y || echo "INSTALL FAILED: moonlight (modrinth)"
packwiz modrinth install "supermartijn642s-core-lib" -y || echo "INSTALL FAILED: supermartijn642s-core-lib (modrinth)"
packwiz modrinth install "supermartijn642s-config-lib" -y || echo "INSTALL FAILED: supermartijn642s-config-lib (modrinth)"
packwiz modrinth install "fusion-connected-textures" -y || echo "INSTALL FAILED: fusion-connected-textures (modrinth)"
packwiz curseforge install "framework" -y --category mc-mods || echo "INSTALL FAILED: framework (curseforge)"
packwiz modrinth install "corgilib" -y || echo "INSTALL FAILED: corgilib (modrinth)"
packwiz modrinth install "terrablender" -y || echo "INSTALL FAILED: terrablender (modrinth)"
packwiz modrinth install "oh-the-trees-youll-grow" -y || echo "INSTALL FAILED: oh-the-trees-youll-grow (modrinth)"
packwiz modrinth install "lithostitched" -y || echo "INSTALL FAILED: lithostitched (modrinth)"
packwiz modrinth install "cristel-lib" -y || echo "INSTALL FAILED: cristel-lib (modrinth)"
packwiz modrinth install "lionfish-api" -y || echo "INSTALL FAILED: lionfish-api (modrinth)"
packwiz modrinth install "owo-lib" -y || echo "INSTALL FAILED: owo-lib (modrinth)"
packwiz modrinth install "sophisticated-core" -y || echo "INSTALL FAILED: sophisticated-core (modrinth)"
packwiz modrinth install "guideme" -y || echo "INSTALL FAILED: guideme (modrinth)"
packwiz modrinth install "bookshelf-lib" -y || echo "INSTALL FAILED: bookshelf-lib (modrinth)"
packwiz modrinth install "prickle" -y || echo "INSTALL FAILED: prickle (modrinth)"
packwiz modrinth install "cloth-config" -y || echo "INSTALL FAILED: cloth-config (modrinth)"
packwiz modrinth install "searchables" -y || echo "INSTALL FAILED: searchables (modrinth)"
packwiz modrinth install "athena-ctm" -y || echo "INSTALL FAILED: athena-ctm (modrinth)"

# enforce sides from the mod list
# find_mod SLUG PATTERN: prints the .pw.toml for SLUG - exact file stem first, else a whole-token
# match in the file text ignoring the display-name line (never a substring: mekanism must not
# match mekanism-generators, and 'Mekanism Generators' must not count as mekanism)
find_mod() {
  if [ -f "mods/$1.pw.toml" ]; then echo "mods/$1.pw.toml"; return; fi
  for m in mods/*.pw.toml; do
    if grep -v -E "^[[:space:]]*name[[:space:]]*=" "$m" 2>/dev/null | grep -q -i -E "(^|[^A-Za-z0-9._-])$2([^A-Za-z0-9._-]|$)"; then echo "$m"; return; fi
  done
  true
}
f=$(find_mod "mouse-tweaks" "mouse-tweaks"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: mouse-tweaks (no .pw.toml found)"
f=$(find_mod "controlling" "controlling"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: controlling (no .pw.toml found)"
f=$(find_mod "sodium" "sodium"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: sodium (no .pw.toml found)"
f=$(find_mod "iris" "iris"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: iris (no .pw.toml found)"
f=$(find_mod "entityculling" "entityculling"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: entityculling (no .pw.toml found)"
f=$(find_mod "immediatelyfast" "immediatelyfast"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: immediatelyfast (no .pw.toml found)"
f=$(find_mod "alternate-current" "alternate-current"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"server\"/" "$f" || printf 'side = "server"\n' >> "$f") || echo "SIDE NOT SET: alternate-current (no .pw.toml found)"
f=$(find_mod "badoptimizations" "badoptimizations"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: badoptimizations (no .pw.toml found)"
f=$(find_mod "dynamic-fps" "dynamic-fps"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: dynamic-fps (no .pw.toml found)"
f=$(find_mod "chunky" "chunky"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"server\"/" "$f" || printf 'side = "server"\n' >> "$f") || echo "SIDE NOT SET: chunky (no .pw.toml found)"
f=$(find_mod "searchables" "searchables"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: searchables (no .pw.toml found)"
f=$(find_mod "athena-ctm" "athena-ctm"); [ -n "$f" ] && (grep -q "^side" "$f" && sed -i "" "s/^side = .*/side = \"client\"/" "$f" || printf 'side = "client"\n' >> "$f") || echo "SIDE NOT SET: athena-ctm (no .pw.toml found)"
packwiz refresh
